#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("IGDB_demo_client.Resource", IsApplication=true)]

namespace IGDB_demo_client
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CustomAdapter.Resource.String.ApplicationName = global::IGDB_demo_client.Resource.String.ApplicationName;
			global::CustomAdapter.Resource.String.Hello = global::IGDB_demo_client.Resource.String.Hello;
			global::Entities.Resource.String.ApplicationName = global::IGDB_demo_client.Resource.String.ApplicationName;
			global::Entities.Resource.String.Hello = global::IGDB_demo_client.Resource.String.Hello;
			global::SAL.Resource.String.ApplicationName = global::IGDB_demo_client.Resource.String.ApplicationName;
			global::SAL.Resource.String.Hello = global::IGDB_demo_client.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int buttonBuscar = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int buttonVideo = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int editTextGame = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int imageViewGame = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int imageViewGameCover = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int listViewGames = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int scrollView1 = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int textView1 = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int textViewGameName = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int textViewGameTitle = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int textViewIdGame = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int textViewSummary = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int game_detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int listview_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
